// Generated by bynkc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function double(x: number): number {
  return x * 2;
}

export function quadruple(x: number): number {
  return double(double(x));
}

