// Generated by karnc — do not edit by hand.
// commons c

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Alpha } from "../a/main.js";
import { Beta } from "../b/main.js";

export interface Combo {
  readonly count: Alpha;
  readonly label: Beta;
}

export const Combo = {
};

