// Generated by karnc — do not edit by hand.
// context commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export const authorise = {
  async call(amount: number, deps: {}): Promise<Result<number, number>> {
    return Promise.resolve(Ok(amount));
  },
};

export function makeSurface(deps: Parameters<typeof authorise.call>[1]) {
  return {
    async authorise(amount: number): Promise<Result<number, number>> {
      return authorise.call(amount, deps);
    },
  };
}

