// Generated by bynkc — do not edit by hand.
// context commerce

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent } from "./runtime.js";

export interface ReserveEvent {
  readonly sku: string;
  readonly qty: number;
}

export const ReserveEvent = {
};

export interface Clock {
  now(): Promise<number>;
}

export const ClockToken: unique symbol = Symbol("Clock");

export class SystemClock implements Clock {
  async now(): Promise<number> {
    return 0;
  }
}

export const SystemClockProvider = { token: ClockToken, factory: () => new SystemClock() };

export interface InventoryState {
  readonly history: Array<{ t: number; v: ReserveEvent }>;
}

const __InventoryRegistry = new StateRegistry();
function __zeroOfInventoryState(): InventoryState { return { history: [] }; }

export class Inventory {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<InventoryState> {
    const stored = await this.state.storage.get<InventoryState>("state");
    return stored ?? __zeroOfInventoryState();
  }

  private async commitState(s: InventoryState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async reserve(sku: string, qty: number, deps: { Clock: Clock }): Promise<void> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      const __r0 = await (async () => { const __now = await deps.Clock.now(); __state.history.push({ t: __now, v: { sku, qty } }); for (let __i = __state.history.length - 1; __i >= 0; __i--) { if (__state.history[__i].t < __now - 2592000000) __state.history.splice(__i, 1); } return undefined; })();
      return undefined;
    })();
    await this.commitState(__state);
    return __result;
  }

  async recentSkus(n: number, deps: {}): Promise<readonly string[]> {
    const __state = await this.loadState();
    return ((() => ((() => __state.history.slice(Math.max(0, __state.history.length - Math.max(0, n))).reverse().map((__e) => __e.v)))().map((__x) => ((e) => e.sku)(__x))))();
  }

  async countSince(t: number, deps: {}): Promise<number> {
    const __state = await this.loadState();
    return ((() => __state.history.filter((__e) => __e.t >= (t)).map((__e) => __e.v)))().length;
  }

}

export function __makeInventory(key: string, env?: { INVENTORY?: DurableObjectNamespace }): Inventory {
  return makeAgent(__InventoryRegistry, env?.INVENTORY, key, (state) => new Inventory(state));
}

export function __resetAgents(): void {
  __InventoryRegistry.reset();
}

