// Generated by bynkc — do not edit by hand.
// context auth.sessions

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import * as tokens from "../tokens.js";

export const login = {
  async call(secret: string, deps: { Jwt: tokens.Jwt }): Promise<string> {
    const token = await deps.Jwt.sign("u1", secret);
    return token;
  },
};

export interface AuthSessionsDeps {
  readonly Jwt: tokens.Jwt;
}

export function makeSurface(deps: AuthSessionsDeps) {
  return {
    async login(secret: string): Promise<string> {
      return login.call(secret, deps);
    },
  };
}

