// Generated by karnc — do not edit by hand.
// context platform.time

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Clock {
  now(): Promise<number>;
}

export const ClockToken: unique symbol = Symbol("Clock");

export class SystemClock implements Clock {
  async now(): Promise<number> {
    return 0;
  }
}

export const SystemClockProvider = { token: ClockToken, factory: () => new SystemClock() };

