// Generated by karnc — do not edit by hand.
// composition root for `shop.orders` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";
import * as karn__binding from "../../karn-cloudflare.js";

export interface Env {
}

export function compose(env: Env) {
  const Clock = new karn__binding.ClockProvider();
  const Logger = new karn__binding.LoggerProvider();
  const deps = { Clock, Logger };
  return {
    async ordering(sku: any) {
      return handlers.ordering.call(sku, deps);
    },
  };
}
