// Generated by bynkc — do not edit by hand.
// composition root for `items` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async http_PUT_items_Param_id(id: any, body: any) {
      return handlers.api.http_PUT_items_Param_id(id, body, deps);
    },
  };
}
