// Generated by bynkc — do not edit by hand.
// test target: commerce.money

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_money from "./../commerce/money.js";

class AssertionError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number) {
    super(`assertion failed at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkAssertionFailure(location: string, start: number, end: number) {
  return new AssertionError(location, start, end);
}
function __bynkAssert(cond: boolean, location: string, start: number, end: number): void {
  if (!cond) { throw __bynkAssertionFailure(location, start, end); }
}

function makeTestDeps() {
  return {  };
}

async function test_money_rejects_negative() {
  try {
    const deps = {};
    const { Money } = commerce_money as any;
    const m = Money.fromMinorUnits(-1);
    if (!(m.tag === "Err")) { throw __bynkAssertionFailure("tests/money.test.bynk:4:12", 104, 115); }
    return { pass: true };
  } catch (e) {
    if (e instanceof AssertionError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_money_accepts_positive() {
  try {
    const deps = {};
    const { Money } = commerce_money as any;
    const m = Money.fromMinorUnits(10);
    if (!(m.tag === "Ok")) { throw __bynkAssertionFailure("tests/money.test.bynk:9:12", 203, 213); }
    return { pass: true };
  } catch (e) {
    if (e instanceof AssertionError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "money rejects negative", ...(await test_money_rejects_negative()) });
  results.push({ name: "money accepts positive", ...(await test_money_accepts_positive()) });
  return results;
}
