// Generated by karnc — do not edit by hand.
// context shop.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import * as karn from "../../karn.js";

export const ordering = {
  async call(sku: string, deps: { Secrets: karn.Secrets }): Promise<string> {
    const key = await deps.Secrets.get("API_KEY");
    switch (key.tag) {
      case "Some": {
        const k = key.value;
        return k;
      }
      case "None": {
        return "missing";
      }
    }
    throw new Error("non-exhaustive match");
  },
};

