// Generated by karnc — do not edit by hand.
// context cart

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export type CartId = string & { readonly __brand: "cart.CartId" };

export const CartId = {
  of(value: string): Result<CartId, ValidationError> {
    return Ok(value as CartId);
  },
  unsafe(value: string): CartId {
    return value as CartId;
  },
};

export interface CartEntityState {
  readonly items: number;
}

export class CartEntity {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<CartEntityState> {
    return (await this.state.storage.get<CartEntityState>("state"))!;
  }

  private async commitState(s: CartEntityState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async total(deps: {}): Promise<number> {
    const currentState = await this.loadState();
    return currentState.items;
  }

}

