// Generated by bynkc — do not edit by hand.
// test target: commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_payment from "./../commerce/payment.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_constructs_AuthId_from_inside_the_test() {
  try {
    const deps = makeTestDeps();
    const { AuthId } = commerce_payment as any;
    const id = AuthId.unsafe("AUTH-12345678");
    if (!(true)) { throw __bynkExpectFailure("tests/payment.test.bynk:6:12", 256, 260, "expect true"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "constructs AuthId from inside the test", ...(await test_constructs_AuthId_from_inside_the_test()) });
  return results;
}
