// Generated by bynkc — do not edit by hand.
// test target: demo.meter

import { Ok, Err, Some, None, makeTestState, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_meter from "./../demo/meter.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_a_fresh_Meter_key_reads_nested_zeros() {
  try {
    demo_meter.__resetAgents();
    const deps = makeTestDeps();
    const { Meter, MeterError, MeterId, Totals, __makeMeter, hits } = demo_meter as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/demo/meter.bynk:8:20", 196, 201, "expect false");
          }
          case "Ok": {
            const id = __d.value;
            const reading = await hits.call(id, deps);
            switch (reading.tag) {
              case "Ok": {
                const n = reading.value;
                return __bynkExpect((n === 0), "tests/demo/meter.bynk:12:22", 288, 294, "expect n == 0");
              }
              case "Err": {
                return __bynkExpect((false), "tests/demo/meter.bynk:13:22", 316, 321, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(MeterId.of("fresh")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "a fresh Meter key reads nested zeros", ...(await test_a_fresh_Meter_key_reads_nested_zeros()) });
  return results;
}
