//! Per-Worker composition root generation (v0.8 §4.5, v0.9 §5.1).
//!
//! Each Worker's `compose.ts` exports a `compose(env)` function that
//! assembles the context's deps and returns the surface the entry point
//! invokes — `on call` services for the internal Service Binding protocol
//! plus `on http` route wrappers for the external HTTP router.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::ast::*;
use crate::emitter::http_handler_method_name;
use crate::emitter::wrangler::{agent_binding_name, consumed_binding_name};
use crate::project::UnitTable;

pub fn emit_worker_compose(
    context: &str,
    table: &UnitTable,
    consumes: &[String],
    aliases: &HashMap<String, String>,
    unit_tables: &HashMap<String, UnitTable>,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by karnc — do not edit by hand.");
    let _ = writeln!(out, "// composition root for `{context}` Worker.");
    writeln!(out).unwrap();
    let _ = aliases; // alias surface keys are folded into handler deps directly.
    let _ = unit_tables;

    let _ = writeln!(
        out,
        "import {{ type ServiceBinding }} from \"../../runtime.js\";"
    );
    let _ = writeln!(out, "import * as handlers from \"./handlers.js\";");
    writeln!(out).unwrap();

    let mut sorted_consumes: Vec<&String> = consumes.iter().collect();
    sorted_consumes.sort();

    // Env shape: one Service Binding per consumed context + DO bindings.
    let _ = writeln!(out, "export interface Env {{");
    for t in &sorted_consumes {
        let bind = consumed_binding_name(t);
        let _ = writeln!(out, "  {bind}: ServiceBinding;");
    }
    let mut agent_names: Vec<&String> = table.agents.keys().collect();
    agent_names.sort();
    for a in &agent_names {
        let bind = agent_binding_name(a);
        let _ = writeln!(out, "  {bind}: DurableObjectNamespace;");
    }
    let _ = writeln!(out, "}}");
    writeln!(out).unwrap();

    if !agent_names.is_empty() {
        let _ = writeln!(
            out,
            "type DurableObjectNamespace = {{ idFromName(name: string): {{ toString(): string }}; get(id: any): any }};"
        );
        writeln!(out).unwrap();
    }

    let _ = writeln!(out, "export function compose(env: Env) {{");

    // Capabilities: instantiate the local provider for each capability.
    let mut provider_caps: Vec<&String> = table.providers.keys().collect();
    provider_caps.sort();
    let mut deps_entries: Vec<String> = Vec::new();
    for cap in &provider_caps {
        let provider = table.providers.get(*cap).unwrap();
        let provider_ts = &provider.provider_name.name;
        deps_entries.push(format!("{cap}: new handlers.{provider_ts}()"));
    }
    // env passes through so handlers' cross-context calls (Service Bindings)
    // and agent instantiations (Durable Object namespaces) can reach it.
    if !sorted_consumes.is_empty() || !table.agents.is_empty() {
        deps_entries.push("env".to_string());
    }
    let _ = writeln!(out, "  const deps = {{ {} }};", deps_entries.join(", "));

    // Local-surface object: one async wrapper per service operation plus
    // one wrapper per `on http` handler.
    let mut service_names: Vec<&String> = table.services.keys().collect();
    service_names.sort();
    let _ = writeln!(out, "  return {{");
    for sname in &service_names {
        let service = table.services.get(*sname).unwrap();
        for h in &service.handlers {
            match &h.kind {
                HandlerKind::Call => {
                    emit_call_wrapper(&mut out, sname, h);
                }
                HandlerKind::Http { method, path } => {
                    emit_http_wrapper(&mut out, sname, h, *method, path);
                }
            }
        }
    }
    let _ = writeln!(out, "  }};");

    let _ = writeln!(out, "}}");
    out
}

fn emit_call_wrapper(out: &mut String, sname: &str, h: &Handler) {
    let param_decls: Vec<String> = h
        .params
        .iter()
        .map(|p| format!("{}: any", p.name.name))
        .collect();
    let param_args: Vec<String> = h.params.iter().map(|p| p.name.name.clone()).collect();
    let _ = writeln!(out, "    async {sname}({}) {{", param_decls.join(", "));
    let _ = writeln!(
        out,
        "      return handlers.{sname}.call({}{}deps);",
        param_args.join(", "),
        if param_args.is_empty() { "" } else { ", " },
    );
    let _ = writeln!(out, "    }},");
}

fn emit_http_wrapper(out: &mut String, sname: &str, h: &Handler, method: HttpMethod, path: &str) {
    let method_key = http_handler_method_name(method, path);
    let param_decls: Vec<String> = h
        .params
        .iter()
        .map(|p| format!("{}: any", p.name.name))
        .collect();
    let param_args: Vec<String> = h.params.iter().map(|p| p.name.name.clone()).collect();
    let _ = writeln!(out, "    async {method_key}({}) {{", param_decls.join(", "));
    let _ = writeln!(
        out,
        "      return handlers.{sname}.{method_key}({}{}deps);",
        param_args.join(", "),
        if param_args.is_empty() { "" } else { ", " },
    );
    let _ = writeln!(out, "    }},");
}
