// Generated by bynkc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function total(): number {
  return 300000 + 30000;
}

export function scaled(): number {
  return 120000 * 3;
}

export function longer(): boolean {
  return 3600000 > 1800000;
}

export function deadline(now: number): number {
  return now + 300000;
}

export function millis(): number {
  return 60000;
}

export function ofInt(n: number): number {
  return n;
}

export function everyUnit(): number {
  return 100 + 1000 + 60000 + 3600000 + 86400000;
}

