// Generated by karnc — do not edit by hand.
// Worker entry point for context `api`.

import { Ok, Err, type Result, type JsonValue, type BoundaryError, boundaryError, matchPath, httpResultToResponse } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_karn/call/")) {
        const servicePath = path.slice("/_karn/call/".length);
        switch (servicePath) {
          default:
            return new Response("Not found", { status: 404 });
        }
      }

      {
        if (method === "GET" && path === "/healthz") {
          const result = await surface.http_GET_healthz(request);
          return httpResultToResponse(result, handlers.serialise_View);
        }
      }
      {
        if (method === "GET" && path === "/ping") {
          const result = await surface.http_GET_ping();
          return httpResultToResponse(result, handlers.serialise_View);
        }
      }
      return new Response("Not Found", { status: 404 });
    } catch (e) {
      return new Response(String(e), { status: 500 });
    }
  },
};
