//! Source-map construction for the emitter (debugging track, slice 1; ADR 0103).
//!
//! The emitter is a one-way string pipe: lowering appends text and discards the
//! `Span` every AST node carries. This module is the position-tracking sidecar
//! that recovers the link. It records **checkpoints** — `(byte offset into the
//! generated buffer, source span)` pairs — at statement, match-arm, and
//! declaration boundaries, and resolves them into a source-map v3 document once
//! the buffer is complete.
//!
//! The design is line-level and statement-anchored (ADR 0103 D1). A checkpoint
//! marks "every generated line from here until the next checkpoint maps to this
//! source span" — which *is* the nearest-enclosing-statement rule (D2): the `?`
//! `Err`-guard and the `match` `case`/binding lines inherit their enclosing
//! statement's span, so a source-map-aware stepper coalesces the lowered
//! expansion into one source step (the slice-0 spike confirmed this).
//!
//! Byte offsets are stable: the buffer only ever grows by appending at the end,
//! so an offset captured mid-emission still points at the same generated line
//! after more text lands. Resolution to line numbers happens once, at the end.

use bynk_syntax::span::{Span, line_col};

/// Accumulates `(generated byte offset, source span)` checkpoints during
/// emission. Lives behind a `RefCell` on `LowerCtx` so the deep lowering chain
/// (which holds `&mut LowerCtx`) and the declaration loop in `emit_project`
/// (which holds the buffer) can both record without fighting the borrow checker.
#[derive(Debug, Default)]
pub(crate) struct SourceMapBuilder {
    /// Recorded in emission order, so byte offsets are non-decreasing.
    checkpoints: Vec<(usize, Span)>,
}

impl SourceMapBuilder {
    pub(crate) fn new() -> Self {
        Self::default()
    }

    /// Record that generated text from `byte_offset` onward originates at
    /// `span`, until the next checkpoint. Callers pass `out.len()` as the
    /// offset, before appending the statement's text.
    pub(crate) fn record(&mut self, byte_offset: usize, span: Span) {
        // Collapse a repeat at the same offset (e.g. a declaration checkpoint
        // immediately followed by its first statement at offset 0 of an empty
        // buffer): the later, more specific span wins.
        if let Some(last) = self.checkpoints.last_mut()
            && last.0 == byte_offset
        {
            last.1 = span;
            return;
        }
        self.checkpoints.push((byte_offset, span));
    }

    /// Serialise to a source-map v3 JSON document. `generated` is the finished
    /// `.ts` buffer; `source_text` is the originating `.bynk` file (embedded as
    /// `sourcesContent` for dev/test fidelity, ADR 0103 D6 — the `workerd`
    /// inspector often cannot resolve a `.bynk` path on disk); `source_name` is
    /// the path recorded in `sources` (project-root-relative, forward slashes).
    ///
    /// Returns `None` when no checkpoint resolves (nothing to map), so the
    /// caller can skip emitting an empty map.
    pub(crate) fn to_v3(
        &self,
        generated: &str,
        source_name: &str,
        source_text: &str,
        generated_file: &str,
    ) -> Option<String> {
        // Resolve each checkpoint to (generated line, source line, source col),
        // all 0-based. Skip any whose source offset falls outside this file's
        // text — a unit can span multiple files, and an item from a sibling
        // file carries a span into *its* source, not this one; mapping it here
        // would be a lie, so it is dropped rather than guessed (D2 covers the
        // gap by inheritance from the nearest in-range checkpoint).
        let line_starts = generated_line_starts(generated);
        let mut resolved: Vec<(usize, usize, usize)> = Vec::new();
        for &(offset, span) in &self.checkpoints {
            if span.start > source_text.len() {
                continue;
            }
            let gen_line = line_of_offset(&line_starts, offset);
            let (sl, sc) = line_col(source_text, span.start);
            resolved.push((gen_line, sl - 1, sc - 1));
        }
        if resolved.is_empty() {
            return None;
        }

        // One mapping per generated line, from the first checkpoint's line to
        // the last generated line, each pointing at the active checkpoint's
        // source position (nearest-preceding = nearest-enclosing).
        let total_lines = line_starts.len();
        let first_line = resolved[0].0;

        let mut mappings = String::new();
        // Leading semicolons for the unmapped lines before the first checkpoint.
        for _ in 0..first_line {
            mappings.push(';');
        }
        // Previous-segment state for VLQ delta encoding (source index, source
        // line, source column persist across lines; generated column resets per
        // line but is always 0 here, so it never needs carrying).
        let (mut prev_src, mut prev_sl, mut prev_sc) = (0i64, 0i64, 0i64);
        let mut ri = 0usize;
        for line in first_line..total_lines {
            if line > first_line {
                mappings.push(';');
            }
            // Advance to the last checkpoint at or before this line.
            while ri + 1 < resolved.len() && resolved[ri + 1].0 <= line {
                ri += 1;
            }
            let (_, sl, sc) = resolved[ri];
            // segment = [genCol=0, srcIndex delta, srcLine delta, srcCol delta]
            vlq_encode(0, &mut mappings);
            vlq_encode(0 - prev_src, &mut mappings);
            vlq_encode(sl as i64 - prev_sl, &mut mappings);
            vlq_encode(sc as i64 - prev_sc, &mut mappings);
            prev_src = 0;
            prev_sl = sl as i64;
            prev_sc = sc as i64;
        }

        Some(format!(
            "{{\"version\":3,\"file\":{},\"sources\":[{}],\"sourcesContent\":[{}],\"names\":[],\"mappings\":{}}}",
            json_string(generated_file),
            json_string(source_name),
            json_string(source_text),
            json_string(&mappings),
        ))
    }
}

/// Byte offset of the start of each generated line (line 0 starts at 0).
fn generated_line_starts(s: &str) -> Vec<usize> {
    let mut starts = vec![0usize];
    for (i, b) in s.bytes().enumerate() {
        if b == b'\n' {
            starts.push(i + 1);
        }
    }
    starts
}

/// 0-based generated line containing `offset`, by binary search over line starts.
fn line_of_offset(line_starts: &[usize], offset: usize) -> usize {
    match line_starts.binary_search(&offset) {
        Ok(i) => i,
        Err(i) => i - 1,
    }
}

/// Base64 VLQ-encode a single signed value, appending to `out`.
fn vlq_encode(value: i64, out: &mut String) {
    const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut v = if value < 0 {
        ((-value) as u64) << 1 | 1
    } else {
        (value as u64) << 1
    };
    loop {
        let mut digit = (v & 0b11111) as usize;
        v >>= 5;
        if v != 0 {
            digit |= 0b100000;
        }
        out.push(B64[digit] as char);
        if v == 0 {
            break;
        }
    }
}

/// Minimal JSON string escaping — enough for paths, source text, and the
/// `mappings` (which is pure ASCII). Avoids a serde dependency for one field.
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vlq_matches_known_values() {
        let mut s = String::new();
        vlq_encode(0, &mut s);
        assert_eq!(s, "A");
        s.clear();
        vlq_encode(1, &mut s);
        assert_eq!(s, "C");
        s.clear();
        vlq_encode(-1, &mut s);
        assert_eq!(s, "D");
        s.clear();
        vlq_encode(16, &mut s);
        assert_eq!(s, "gB");
    }

    #[test]
    fn line_of_offset_finds_the_line() {
        // "a\nbb\nc"  -> line starts at 0, 2, 5
        let starts = generated_line_starts("a\nbb\nc");
        assert_eq!(starts, vec![0, 2, 5]);
        assert_eq!(line_of_offset(&starts, 0), 0);
        assert_eq!(line_of_offset(&starts, 1), 0);
        assert_eq!(line_of_offset(&starts, 2), 1); // start of line 1
        assert_eq!(line_of_offset(&starts, 4), 1);
        assert_eq!(line_of_offset(&starts, 5), 2);
    }

    #[test]
    fn empty_builder_serialises_to_none() {
        let b = SourceMapBuilder::new();
        assert!(b.to_v3("x\n", "a.bynk", "a", "x.ts").is_none());
    }

    #[test]
    fn maps_each_generated_line_to_nearest_preceding_checkpoint() {
        // Source: two statements on source lines 2 and 3 (1-based).
        //   line1: header
        //   line2: stmtA        (byte offset of 'A' line)
        //   line3: stmtB
        let source = "header\nstmtA\nstmtB\n";
        let off_a = source.find("stmtA").unwrap(); // span start for stmt A
        let off_b = source.find("stmtB").unwrap();

        // Generated: 4 lines. Lines 1+2 come from stmtA, lines 3+4 from stmtB.
        let generated = "g0\ng1\ng2\ng3\n";
        let g_line2 = generated.find("g2").unwrap();

        let mut b = SourceMapBuilder::new();
        b.record(0, Span::new(off_a, off_a + 5)); // generated line 0 -> source line 2
        b.record(g_line2, Span::new(off_b, off_b + 5)); // generated line 2 -> source line 3

        let json = b.to_v3(generated, "x.bynk", source, "x.ts").unwrap();
        // The document is built by hand (no serde here); assert on its shape.
        assert!(json.contains("\"version\":3"));
        assert!(json.contains("\"sources\":[\"x.bynk\"]"));
        assert!(json.contains("\"file\":\"x.ts\""));
        assert!(json.contains(&format!("\"sourcesContent\":[{}]", json_string(source))));

        // Decode mappings: each line should resolve to source line 1 then 2
        // (0-based): g0,g1 -> src line 1; g2,g3 -> src line 2. The trailing
        // newline yields one more (empty) line, which inherits the last
        // checkpoint — harmless, and standard for maps over `\n`-terminated TS.
        let mappings = extract_mappings(&json);
        let lines = decode_mapping_src_lines(&mappings);
        assert_eq!(lines, vec![Some(1), Some(1), Some(2), Some(2), Some(2)]);
    }

    /// Pull the `mappings` string back out of the hand-built JSON document.
    fn extract_mappings(json: &str) -> String {
        let key = "\"mappings\":\"";
        let start = json.find(key).unwrap() + key.len();
        let rest = &json[start..];
        let end = rest.find('"').unwrap();
        rest[..end].to_string()
    }

    /// Decode the source line (0-based) each generated line maps to, for the
    /// single-segment-per-line maps this builder emits.
    fn decode_mapping_src_lines(mappings: &str) -> Vec<Option<i64>> {
        let mut out = Vec::new();
        let mut src_line = 0i64;
        for line in mappings.split(';') {
            if line.is_empty() {
                out.push(None);
                continue;
            }
            let fields = vlq_decode(line);
            // [genCol, srcIdx, srcLineDelta, srcCol]
            src_line += fields[2];
            out.push(Some(src_line));
        }
        out
    }

    fn vlq_decode(s: &str) -> Vec<i64> {
        const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        let idx = |c: u8| B64.iter().position(|&b| b == c).unwrap() as i64;
        let mut out = Vec::new();
        let (mut shift, mut acc) = (0i64, 0i64);
        for &c in s.as_bytes() {
            let d = idx(c);
            acc += (d & 0b11111) << shift;
            if d & 0b100000 != 0 {
                shift += 5;
            } else {
                let neg = acc & 1 == 1;
                let mag = acc >> 1;
                out.push(if neg { -mag } else { mag });
                shift = 0;
                acc = 0;
            }
        }
        out
    }
}
