// Generated by bynkc — do not edit by hand.
// commons b

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export type Beta = string & { readonly __brand: "Beta" };

export const Beta = {
  of(value: string): Result<Beta, ValidationError> {
    if (!(value.length > 0)) {
      return Err({ field: "Beta", message: "must be non-empty", value });
    }
    return Ok(value as Beta);
  },
  unsafe(value: string): Beta {
    return value as Beta;
  },
};

