// Generated by karnc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function xor(a: boolean, b: boolean): boolean {
  return (a || b) && !(a && b);
}

