// Generated by bynkc — do not edit by hand.
// test target: commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_payment from "./../commerce/payment.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

class SilentLogger {
  async log(msg: string): Promise<void> {
    const { AuthId, PaymentError } = commerce_payment as any;
    return undefined;
  }
}

function makeTestDeps() {
  return { Logger: new SilentLogger() };
}

async function test_case_one() {
  try {
    const deps = makeTestDeps();
    const { AuthId, PaymentError, authorise } = commerce_payment as any;
    const r = await authorise.call(10, deps);
    if (!(r.tag === "Ok")) { throw __bynkExpectFailure("tests/payment.test.bynk:10:12", 180, 190, "expect r is Ok(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_case_two() {
  try {
    const deps = makeTestDeps();
    const { AuthId, PaymentError, authorise } = commerce_payment as any;
    const r = await authorise.call(20, deps);
    if (!(r.tag === "Ok")) { throw __bynkExpectFailure("tests/payment.test.bynk:15:12", 259, 269, "expect r is Ok(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_case_three() {
  try {
    const deps = makeTestDeps();
    const { AuthId, PaymentError, authorise } = commerce_payment as any;
    const r = await authorise.call(0, deps);
    if (!(r.tag === "Err")) { throw __bynkExpectFailure("tests/payment.test.bynk:20:12", 339, 350, "expect r is Err(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "case one", ...(await test_case_one()) });
  results.push({ name: "case two", ...(await test_case_two()) });
  results.push({ name: "case three", ...(await test_case_three()) });
  return results;
}
