// Generated by bynkc — do not edit by hand.
// test target: commerce.money

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_money from "./../commerce/money.js";

class AssertionError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number) {
    super(`assertion failed at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkAssertionFailure(location: string, start: number, end: number) {
  return new AssertionError(location, start, end);
}
function __bynkAssert(cond: boolean, location: string, start: number, end: number): void {
  if (!cond) { throw __bynkAssertionFailure(location, start, end); }
}

function makeTestDeps() {
  return {  };
}

async function test_block_arm_assert() {
  try {
    const deps = {};
    const { Money } = commerce_money as any;
    const m = Money.fromMinorUnits(10);
    void (((__d) => {
        switch (__d.tag) {
          case "Ok": {
            if (!(true)) { throw __bynkAssertionFailure("tests/money.test.bynk:6:16", 133, 137); }
            return undefined;
          }
          case "Err": {
            if (!(false)) { throw __bynkAssertionFailure("tests/money.test.bynk:9:16", 179, 184); }
            return undefined;
          }
        }
        throw new Error("non-exhaustive match");
      })(m));
    return { pass: true };
  } catch (e) {
    if (e instanceof AssertionError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "block-arm assert", ...(await test_block_arm_assert()) });
  return results;
}
