// Generated by karnc — do not edit by hand.
// composition root for `demo` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const Logger = new handlers.ConsoleLogger();
  const Store = new handlers.LoggingStore({ Logger });
  const deps = { Logger, Store };
  return {
    async api(key: any) {
      return handlers.api.call(key, deps);
    },
  };
}
