// Generated by karnc — do not edit by hand.
// adapter karn.cloudflare

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../runtime.js";

export interface Kv {
  get(key: string): Promise<Option<string>>;
  put(key: string, value: string): Promise<void>;
  delete(key: string): Promise<void>;
}

export const KvToken: unique symbol = Symbol("Kv");

