// Generated by karnc — do not edit by hand.
// composition root

import * as ids_gen from "./ids/gen.js";
import * as karn__binding from "./karn-cloudflare.js";

export function composeApp() {
  const ids_genDeps = { Random: new karn__binding.RandomProvider() };
  const ids_genSurface = ids_gen.makeSurface(ids_genDeps);

  return {
    gen: ids_genSurface,
  };
}
