// Generated by bynkc — do not edit by hand.
// composition root

import * as shop_orders from "./shop/orders.js";
import * as bynk__binding from "./bynk-cloudflare.js";

export function composeApp() {
  const shop_ordersDeps = { Stamp: new shop_orders.ClockStamp({ Clock: new bynk__binding.ClockProvider() }) };
  const shop_ordersSurface = shop_orders.makeSurface(shop_ordersDeps);

  return {
    orders: shop_ordersSurface,
  };
}
