// Generated by bynkc — do not edit by hand.
// context commerce.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Money as __CommonsMoney } from "./money.js";

export type Money = __CommonsMoney & { readonly __ctxBrand: "commerce.orders" };

export interface Order {
  readonly total: Money;
}

export const Order = {
};

