// Generated by bynkc — do not edit by hand.
// commons fx

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export async function run(f: (a0: number) => Promise<number>, x: number): Promise<number> {
  const y = await f(x);
  return y + 1;
}

