// Generated by bynkc — do not edit by hand.
// context commerce.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Money as __CommonsMoney } from "./money.js";
import { AuthId } from "./payment.js";

export type Money = __CommonsMoney & { readonly __ctxBrand: "commerce.orders" };

export interface Order {
  readonly total: Money;
  readonly authId: AuthId;
}

export const Order = {
};

export type OrderError =
    { readonly tag: "EmptyCart" }
  | { readonly tag: "TooManyItems" };

export const OrderError = {
  EmptyCart: { tag: "EmptyCart" } as OrderError,
  TooManyItems: { tag: "TooManyItems" } as OrderError,
};

