// Generated by karnc — do not edit by hand.
// context mailer

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export interface EmailJob {
  readonly to: string;
  readonly subject: string;
}

export const EmailJob = {
};

export const outbox = {
  async queue_outbox_0(message: EmailJob, deps: {}): Promise<Result<void, string>> {
    return Ok(undefined);
  },
};

export function serialise_EmailJob(value: EmailJob): JsonValue {
  return {
    to: value.to as JsonValue,
    subject: value.subject as JsonValue,
  };
}

export function deserialise_EmailJob(json: JsonValue, path: string = "$"): Result<EmailJob, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["to"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.to`, expected: "string", actual: typeof obj["to"] });
  }
  const __to = obj["to"];
  if (typeof obj["subject"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.subject`, expected: "string", actual: typeof obj["subject"] });
  }
  const __subject = obj["subject"];
  return Ok({ to: __to, subject: __subject } as EmailJob);
}


export function serialise_Result_Unit_String(value: Result<void, string>): JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: null };
  return { kind: "Err", error: value.error as JsonValue };
}

export function deserialise_Result_Unit_String(json: JsonValue, path: string = "$"): Result<Result<void, string>, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (obj["kind"] === "Ok") {
  const __v = undefined;
    return Ok(Ok(__v) as Result<void, string>);
  } else if (obj["kind"] === "Err") {
  if (typeof obj["error"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.error`, expected: "string", actual: typeof obj["error"] });
  }
  const __e = obj["error"];
    return Ok(Err(__e) as Result<void, string>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

