// Generated by karnc — do not edit by hand.
// composition root for `shop.payment` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const Bank = new handlers.StubBank();
  const deps = { Bank };
  return {
    async authorise(cents: any) {
      return handlers.authorise.call(cents, deps);
    },
  };
}
