// Generated by bynkc — do not edit by hand.
// test target: commerce.orders

import { Ok, Err, Some, None, makeTestState, type Result, type Option, type ValidationError } from "../runtime.js";
import * as commerce_orders from "./../commerce/orders.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_agent_place_reports_Ok() {
  try {
    commerce_orders.__resetAgents();
    const deps = makeTestDeps();
    const { Order, OrderError, OrderId, __makeOrder } = commerce_orders as any;
    const r = await __makeOrder(OrderId.unsafe("ORD-1")).place(50, deps);
    if (!(r.tag === "Ok")) { throw __bynkExpectFailure("tests/orders.test.bynk:4:12", 123, 133, "expect r is Ok(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_agent_place_reports_NotPlaced_for_zero() {
  try {
    commerce_orders.__resetAgents();
    const deps = makeTestDeps();
    const { Order, OrderError, OrderId, __makeOrder } = commerce_orders as any;
    const r = await __makeOrder(OrderId.unsafe("ORD-2")).place(0, deps);
    if (!(r.tag === "Err")) { throw __bynkExpectFailure("tests/orders.test.bynk:9:12", 253, 264, "expect r is Err(_)"); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "agent place reports Ok", ...(await test_agent_place_reports_Ok()) });
  results.push({ name: "agent place reports NotPlaced for zero", ...(await test_agent_place_reports_NotPlaced_for_zero()) });
  return results;
}
