// Generated by bynkc — do not edit by hand.
// context ids.gen

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Uuid } from "../bynk.js";

import * as bynk from "../bynk.js";

export const generate = {
  async call(deps: { Random: bynk.Random }): Promise<Uuid> {
    const id = await deps.Random.uuid();
    return id;
  },
};

export interface IdsGenDeps {
  readonly Random: bynk.Random;
}

export function makeSurface(deps: IdsGenDeps) {
  return {
    async generate(): Promise<Uuid> {
      return generate.call(deps);
    },
  };
}

