// Generated by karnc — do not edit by hand.
// composition root

import * as ops_metrics from "./ops/metrics.js";
import * as platform_time from "./platform/time.js";

export function composeApp() {
  const ops_metricsDeps = { Stamp: new ops_metrics.ClockStamp({ Clock: new platform_time.SystemClock() }) };
  const ops_metricsSurface = ops_metrics.makeSurface(ops_metricsDeps);

  return {
    metrics: ops_metricsSurface,
  };
}
