// Generated by bynkc — do not edit by hand.
// commons test

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function classify(n: number): string {
  return (n < 10 ? "small" : (n < 100 ? "medium" : "large"));
}

