// Generated by bynkc — do not edit by hand.
// composition root for `shop.orders` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";
import * as bynk__binding from "../../bynk-cloudflare.js";

export interface Env {
}

export function compose(env: Env) {
  const Secrets = new bynk__binding.SecretsProvider(env);
  const deps = { Secrets };
  return {
    async ordering(sku: any) {
      return handlers.ordering.call(sku, deps);
    },
  };
}
