// Generated by bynkc — do not edit by hand.
// context room

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type Connection, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, heldStore, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export interface ServerFrame {
  readonly text: string;
}

export const ServerFrame = {
};

export interface RoomState {
}

const __RoomRegistry = new StateRegistry();
function __zeroOfRoomState(): RoomState { return {}; }

export class Room {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<RoomState> {
    const stored = await this.state.storage.get<RoomState>("state");
    if (stored === undefined) return __zeroOfRoomState();
    const __merged = { ...__zeroOfRoomState(), ...stored };
    return __merged;
  }

  private async commitState(s: RoomState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async join(u: string, conn: Connection<ServerFrame>, deps: {}): Promise<void> {
    const __state = await this.loadState();
    const __r0 = await ((heldStore<Connection<ServerFrame>>(this.state, "conns")).set(String(u), conn), undefined);
    return undefined;
  }

  async greet(conn: Connection<ServerFrame>, deps: {}): Promise<void> {
    const __state = await this.loadState();
    const __r0 = await (conn).send({ text: "welcome" });
    const __r1 = await (conn).close();
    return undefined;
  }

  async leave(u: string, deps: {}): Promise<void> {
    const __state = await this.loadState();
    const __r0 = await ((heldStore<Connection<ServerFrame>>(this.state, "conns")).delete(String(u)), undefined);
    return undefined;
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/_bynk/agent/")) {
      const methodName = url.pathname.slice("/_bynk/agent/".length);
      const { args, deps } = (await request.json()) as { args: unknown[]; deps: unknown };
      const result = await (this as any)[methodName](...args, deps);
      return new Response(JSON.stringify(result), { headers: { "content-type": "application/json" } });
    }
    return new Response("Not Found", { status: 404 });
  }

}

export function __makeRoom(key: string, env?: { ROOM?: DurableObjectNamespace }): Room {
  return makeAgent(__RoomRegistry, env?.ROOM, key, (state) => new Room(state));
}

export function __resetAgents(): void {
  __RoomRegistry.reset();
}

