// Generated by bynkc — do not edit by hand.
// context app.demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { Method, Request } from "../bynk.js";

import * as bynk from "../bynk.js";

export const demo = {
  async call(url: string, deps: { Clock: bynk.Clock; Random: bynk.Random; Logger: bynk.Logger; Fetch: bynk.Fetch; Secrets: bynk.Secrets }): Promise<number> {
    const __r0 = await deps.Logger.info("probe");
    const __r1 = await deps.Clock.now();
    const __r2 = await deps.Random.uuid();
    const n = await deps.Random.int(0, 10);
    const tok = await deps.Secrets.get("TOKEN");
    const req = { method: Method.Get, url: url, contentType: None, authorization: tok, body: None };
    const res = await deps.Fetch.send(req);
    switch (res.tag) {
      case "Ok": {
        const r = res.value;
        return r.status;
      }
      case "Err": {
        return n;
      }
    }
    throw new Error("non-exhaustive match");
  },
};

export interface AppDemoDeps {
  readonly Clock: bynk.Clock;
  readonly Fetch: bynk.Fetch;
  readonly Logger: bynk.Logger;
  readonly Random: bynk.Random;
  readonly Secrets: bynk.Secrets;
}

export function makeSurface(deps: AppDemoDeps) {
  return {
    async demo(url: string): Promise<number> {
      return demo.call(url, deps);
    },
  };
}

