// Generated by karnc — do not edit by hand.
// adapter tokens

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

import * as logging from "./logging.js";

export interface Jwt {
  sign(sub: string): Promise<string>;
}

export const JwtToken: unique symbol = Symbol("Jwt");

