// Generated by karnc — do not edit by hand.
// composition root for `ticker` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async cron_clock_0(at: any) {
      return handlers.clock.cron_clock_0(at, deps);
    },
  };
}
