// Generated by karnc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function inRange(x: number, lo: number, hi: number): boolean {
  return x >= lo && x <= hi;
}

