// Generated by karnc — do not edit by hand.
// context greet

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, HttpResult, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export const api = {
  async http_GET_ping(deps: {}): Promise<HttpResult<string>> {
    return HttpResult.Ok("pong");
  },
};

