// Generated by karnc — do not edit by hand.
// composition root for `app.b` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async whoami(__caller: string, ping: any) {
      return handlers.whoami.call(ping, { ...deps, identity: __caller });
    },
  };
}
