// Generated by bynkc — do not edit by hand.
// commons test

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function useValue(r: Result<number, string>): number {
  if (r.tag === "Ok") {
    const n = r.value;
    return n;
  } else {
    return 0;
  }
}

