// Generated by karnc — do not edit by hand.
// composition root

import * as cache_store from "./cache/store.js";
import * as karn_cloudflare__binding from "./karn/cloudflare.binding.js";

export function composeApp(env?: unknown) {
  const cache_storeDeps = { Kv: new karn_cloudflare__binding.WorkersKv(env) };
  const cache_storeSurface = cache_store.makeSurface(cache_storeDeps);

  return {
    store: cache_storeSurface,
  };
}
