// Generated by karnc — do not edit by hand.
// context auth.sessions

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import * as tokens from "../../tokens.js";

export const login = {
  async call(secret: string, deps: { Jwt: tokens.Jwt }): Promise<string> {
    const token = await deps.Jwt.sign("u1", secret);
    return token;
  },
};

