// Generated by karnc — do not edit by hand.
// context commerce.payment

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

import { Money as __CommonsMoney } from "./money.js";

export type Money = __CommonsMoney & { readonly __ctxBrand: "commerce.payment" };

export interface Payment {
  readonly amount: Money;
}

export const Payment = {
};

