// Generated by karnc — do not edit by hand.
// commons pipeline

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function pass(f: (a0: number) => number): (a0: number) => number {
  return f;
}

export function run(f: (a0: number) => Promise<number>): (a0: number) => Promise<number> {
  return f;
}

