// Generated by karnc — do not edit by hand.
// context demo.agt

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent } from "../runtime.js";

export type Id = number & { readonly __brand: "demo.agt.Id" };

export const Id = {
  of(value: number): Result<Id, ValidationError> {
    if (!Number.isInteger(value)) {
      return Err({ field: "Id", message: "must be an integer", value });
    }
    if (!(value >= 0)) {
      return Err({ field: "Id", message: "must be non-negative", value });
    }
    return Ok(value as Id);
  },
  unsafe(value: number): Id {
    return value as Id;
  },
};

export interface ToggleState {
  readonly on: boolean;
}

const __ToggleRegistry = new StateRegistry();
function __zeroOfToggleState(): ToggleState { return { on: false }; }

export class Toggle {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<ToggleState> {
    const stored = await this.state.storage.get<ToggleState>("state");
    return stored ?? __zeroOfToggleState();
  }

  private async commitState(s: ToggleState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async flip(force: boolean, deps: {}): Promise<boolean> {
    const currentState = await this.loadState();
    if (force) {
      await this.commitState({ ...currentState, on: !currentState.on });
      return true;
    } else {
      return false;
    }
  }

}

export function __makeToggle(key: Id, env?: { TOGGLE?: DurableObjectNamespace }): Toggle {
  return makeAgent(__ToggleRegistry, env?.TOGGLE, key, (state) => new Toggle(state));
}

export function __resetAgents(): void {
  __ToggleRegistry.reset();
}

