// Generated by bynkc — do not edit by hand.
// commons calc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function dbl(n: number): number {
  return n + n;
}

