// Generated by bynkc — do not edit by hand.
// commons report

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

import { join } from "../bynk/string.js";

export function csvLine(cells: readonly string[]): string {
  return join(cells, ",");
}

export function roundTrip(line: string): string {
  return join(line.split(","), ",");
}

