// Generated by bynkc — do not edit by hand.
// composition root

import * as auth_sessions from "./auth/sessions.js";
import * as tokens__binding from "./tokens.binding.js";

export function composeApp() {
  const auth_sessionsDeps = { Jwt: new tokens__binding.JoseJwt() };
  const auth_sessionsSurface = auth_sessions.makeSurface(auth_sessionsDeps);

  return {
    sessions: auth_sessionsSurface,
  };
}
