// Generated by karnc — do not edit by hand.
// context commerce.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

import { CustomerId as __CommonsCustomerId, OrderId as __CommonsOrderId } from "./identifiers.js";
import { Money as __CommonsMoney } from "./money.js";

export type CustomerId = __CommonsCustomerId & { readonly __ctxBrand: "commerce.orders" };
export type Money = __CommonsMoney & { readonly __ctxBrand: "commerce.orders" };
export type OrderId = __CommonsOrderId & { readonly __ctxBrand: "commerce.orders" };

export interface Order {
  readonly id: OrderId;
  readonly customer: CustomerId;
  readonly total: Money;
}

export const Order = {
};

