// Generated by bynkc — do not edit by hand.
// commons a

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export type Alpha = number & { readonly __brand: "Alpha" };

export const Alpha = {
  of(value: number): Result<Alpha, ValidationError> {
    if (!Number.isInteger(value)) {
      return Err({ field: "Alpha", message: "must be an integer", value });
    }
    if (!(value > 0)) {
      return Err({ field: "Alpha", message: "must be positive", value });
    }
    return Ok(value as Alpha);
  },
  unsafe(value: number): Alpha {
    return value as Alpha;
  },
};

