// Generated by karnc — do not edit by hand.
// context commerce.orders

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export type OrderId = string & { readonly __brand: "commerce.orders.OrderId" };

export const OrderId = {
  of(value: string): Result<OrderId, ValidationError> {
    if (!new RegExp("^" + "ORD-[0-9]+" + "$").test(value)) {
      return Err({ field: "OrderId", message: "must match /ORD-[0-9]+/", value });
    }
    return Ok(value as OrderId);
  },
  unsafe(value: string): OrderId {
    return value as OrderId;
  },
};

export type OrderStatus =
    { readonly tag: "Pending" }
  | { readonly tag: "Placed" }
  | { readonly tag: "Cancelled" };

export const OrderStatus = {
  Pending: { tag: "Pending" } as OrderStatus,
  Placed: { tag: "Placed" } as OrderStatus,
  Cancelled: { tag: "Cancelled" } as OrderStatus,
};

