// Generated by bynkc — do not edit by hand.
// composition root

import * as forecast_lookup from "./forecast/lookup.js";
import * as bynk__binding from "./bynk-cloudflare.js";
import * as weather__binding from "./weather.binding.js";

export function composeApp() {
  const forecast_lookupDeps = { Weather: new weather__binding.FetchWeather({ Fetch: new bynk__binding.FetchProvider(), Secrets: new bynk__binding.SecretsProvider() }) };
  const forecast_lookupSurface = forecast_lookup.makeSurface(forecast_lookupDeps);

  return {
    lookup: forecast_lookupSurface,
  };
}
