// Generated by bynkc — do not edit by hand.
// test target: demo.slot

import { Ok, Err, Some, None, makeTestState, type Result, type Option, type ValidationError } from "../runtime.js";
import * as demo_slot from "./../demo/slot.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_a_fresh_Slot_key_resolves_to_Empty() {
  try {
    demo_slot.__resetAgents();
    const deps = makeTestDeps();
    const { Label, Slot, SlotError, __makeSlot, resolve } = demo_slot as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/demo/slot.bynk:8:20", 196, 201, "expect false");
          }
          case "Ok": {
            const id = __d.value;
            const outcome = await resolve.call(id, deps);
            switch (outcome.tag) {
              case "Ok": {
                return __bynkExpect((false), "tests/demo/slot.bynk:12:22", 291, 296, "expect false");
              }
              case "Err": {
                const slotError = outcome.error;
                return ((__d) => {
        switch (__d.tag) {
          case "Empty": {
            return __bynkExpect((true), "tests/demo/slot.bynk:14:22", 358, 362, "expect true");
          }
        }
        throw new Error("non-exhaustive match");
      })(slotError);
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(Label.of("fresh")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "a fresh Slot key resolves to Empty", ...(await test_a_fresh_Slot_key_resolves_to_Empty()) });
  return results;
}
