// Generated by bynkc — do not edit by hand.
// composition root

import * as ops_jobs from "./ops/jobs.js";
import * as platform_time from "./platform/time.js";

export function composeApp() {
  const ops_jobsDeps = { Clock: new platform_time.SystemClock() };
  const ops_jobsSurface = ops_jobs.makeSurface(ops_jobsDeps);

  return {
    jobs: ops_jobsSurface,
  };
}
