// Generated by karnc — do not edit by hand.
// commons commerce.money

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Money {
  readonly minorUnits: number;
  readonly currency: string;
}

export const Money = {
};

