// Generated by karnc — do not edit by hand.
// composition root for `notifier` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = { Sender: new handlers.StubSender() };
  return {
    async queue_notify_0(message: any) {
      return handlers.notify.queue_notify_0(message, deps);
    },
  };
}
