// Generated by karnc — do not edit by hand.
// context notifier

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export interface Notification {
  readonly body: string;
}

export const Notification = {
};

export interface Sender {
  send(text: string): Promise<void>;
}

export const SenderToken: unique symbol = Symbol("Sender");

export class StubSender implements Sender {
  async send(text: string): Promise<void> {
    return undefined;
  }
}

export const StubSenderProvider = { token: SenderToken, factory: () => new StubSender() };

export const notify = {
  async queue_notify_0(message: Notification, deps: { Sender: Sender }): Promise<Result<void, string>> {
    const __r0 = await deps.Sender.send(message.body);
    return Ok(undefined);
  },
};

export function serialise_Notification(value: Notification): JsonValue {
  return {
    body: value.body as JsonValue,
  };
}

export function deserialise_Notification(json: JsonValue, path: string = "$"): Result<Notification, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["body"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.body`, expected: "string", actual: typeof obj["body"] });
  }
  const __body = obj["body"];
  return Ok({ body: __body } as Notification);
}


export function serialise_Result_Unit_String(value: Result<void, string>): JsonValue {
  if (value.tag === "Ok") return { kind: "Ok", value: null };
  return { kind: "Err", error: value.error as JsonValue };
}

export function deserialise_Result_Unit_String(json: JsonValue, path: string = "$"): Result<Result<void, string>, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (obj["kind"] === "Ok") {
  const __v = undefined;
    return Ok(Ok(__v) as Result<void, string>);
  } else if (obj["kind"] === "Err") {
  if (typeof obj["error"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.error`, expected: "string", actual: typeof obj["error"] });
  }
  const __e = obj["error"];
    return Ok(Err(__e) as Result<void, string>);
  }
  return Err({ kind: "StructuralMismatch", path, expected: "Ok | Err", actual: String(obj["kind"]) });
}

