// Generated by karnc — do not edit by hand.
// top-level test runner

declare const process: { exit(code: number): never };

import * as test_0 from "./commerce_orders.test.js";
import * as test_1 from "./commerce_payment.test.js";

async function main() {
  const modules = [
    { name: "commerce.orders", run: test_0.run },
    { name: "commerce.payment", run: test_1.run },
  ];
  let passed = 0;
  let failed = 0;
  console.log("Running tests...\n");
  for (const m of modules) {
    console.log(`${m.name}:`);
    const results = await m.run();
    for (const r of results) {
      if (r.pass) { passed++; console.log(`  \u2713 ${r.name}`); } else { failed++; console.log(`  \u2717 ${r.name}`); if (r.error) console.log(`    ${r.error.message}`); }
    }
    console.log("");
  }
  console.log(`${passed} passed, ${failed} failed.`);
  if (failed > 0) process.exit(1);
}

main();
