// Generated by bynkc — do not edit by hand.
// context demo.agt

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, type JsonValue, type BoundaryError } from "../runtime.js";

export type Counter = number & { readonly __brand: "demo.agt.Counter" };

export const Counter = {
  of(value: number): Result<Counter, ValidationError> {
    if (!Number.isInteger(value)) {
      return Err({ field: "Counter", message: "must be an integer", value });
    }
    if (!(value >= 0)) {
      return Err({ field: "Counter", message: "must be non-negative", value });
    }
    return Ok(value as Counter);
  },
  unsafe(value: number): Counter {
    return value as Counter;
  },
};

export type OrderError =
    { readonly tag: "OutOfStock" };

export const OrderError = {
  OutOfStock: { tag: "OutOfStock" } as OrderError,
};

export interface BoxState {
  readonly placed: boolean;
}

const __BoxRegistry = new StateRegistry();
function __zeroOfBoxState(): BoxState { return { placed: false }; }

function __rehydrateBoxState(s: BoxState): void {
  { const __r = ((__v) => typeof __v === "boolean" ? Ok(__v) : Err({ kind: "StructuralMismatch", path: "placed", expected: "boolean", actual: typeof __v } as BoundaryError))((s.placed as unknown as JsonValue)); if (__r.tag === "Err") throw rehydrationViolation("Box", __r.error); }
}

export class Box {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<BoxState> {
    const stored = await this.state.storage.get<BoxState>("state");
    if (stored === undefined) return __zeroOfBoxState();
    const __merged = { ...__zeroOfBoxState(), ...stored };
    __rehydrateBoxState(__merged);
    return __merged;
  }

  private async commitState(s: BoxState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async place(amount: number, deps: {}): Promise<Result<void, OrderError>> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      if (amount > 0) {
        __state.placed = true;
        return Ok(undefined);
      } else {
        return Err(OrderError.OutOfStock);
      }
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeBox(key: Counter, env?: { BOX?: DurableObjectNamespace }): Box {
  return makeAgent(__BoxRegistry, env?.BOX, key, (state) => new Box(state));
}

export function __resetAgents(): void {
  __BoxRegistry.reset();
}

