// Generated by karnc — do not edit by hand.
// composition root for `commerce.payment` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = { Payments: new handlers.StubPayments() };
  return {
    async authorise(amount: any) {
      return handlers.authorise.call(amount, deps);
    },
  };
}
