// Generated by karnc — do not edit by hand.
// Worker entry point for context `commerce.payment`.

import { Ok, Err, type Result, type JsonValue, type BoundaryError, boundaryError } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname.replace(/^\//, "");
    const surface = compose(env);
    try {
      switch (path) {
        case "authorise": {
          const args = await request.json() as JsonValue;
          const __r_amount = handlers.deserialise_Money(args, "$");
          if (__r_amount.tag === "Err") return new Response(JSON.stringify(__r_amount.error), { status: 400, headers: { "content-type": "application/json" } });
          const amount = __r_amount.value;
          const result = await surface.authorise(amount);
          const body = handlers.serialise_Result_AuthId_PaymentError(result);
          return new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
        }
        default:
          return new Response("Not found", { status: 404 });
      }
    } catch (e) {
      return new Response(String(e), { status: 500 });
    }
  },
};
