// Generated by bynkc — do not edit by hand.
// context demo.svc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Counter {
  next(seed: number): Promise<number>;
  reset(): Promise<void>;
}

export const CounterToken: unique symbol = Symbol("Counter");

export class StubCounter implements Counter {
  async next(seed: number): Promise<number> {
    return seed + 1;
  }
  async reset(): Promise<void> {
    return undefined;
  }
}

export const StubCounterProvider = { token: CounterToken, factory: () => new StubCounter() };

