// Generated by bynkc — do not edit by hand.
// context ops.jobs

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

import * as platform_time from "../platform-time/handlers.js";

export const tick = {
  async call(deps: { Clock: platform_time.Clock }): Promise<number> {
    const t = await deps.Clock.now();
    return t;
  },
};

