// Generated by karnc — do not edit by hand.
// commons docs.demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

/**
 * The Money type represents an amount in a specific currency.
 *
 * The minorUnits field is the smallest indivisible unit of the currency
 * (pence for GBP, cents for USD, etc.). The currency field is a three-letter
 * ISO currency code.
 *
 * - minorUnits: integer >= 0
 * - currency: three uppercase letters
 */
export interface Money {
  readonly minorUnits: number;
  readonly currency: string;
}

export const Money = {
};

