// Generated by bynkc — do not edit by hand.
// composition root for `quote` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async quotes(sku: any, price: any) {
      return handlers.quotes.call(sku, price, deps);
    },
  };
}
