// Generated by bynkc — do not edit by hand.
// test target: calc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";
import * as calc from "./../calc.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_doubles() {
  try {
    const deps = {};
    const { dbl } = calc as any;
    if (!(dbl(3) === 6)) { throw __bynkExpectFailure("calc.bynk:7:12", 95, 106, "expect dbl(3) == 6\n  expected: dbl(3) == 6\n  actual:   " + __bynkShow((dbl(3))) + " == " + __bynkShow((6))); }
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "doubles", ...(await test_doubles()) });
  return results;
}
