// Generated by karnc — do not edit by hand.
// composition root for `demo` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const Logger = new handlers.ConsoleLogger();
  const Greeter = new handlers.PoliteGreeter({ Logger });
  const deps = { Greeter, Logger };
  return {
    async hello() {
      return handlers.hello.call(deps);
    },
  };
}
