// Generated by bynkc — do not edit by hand.
// test target: shortener.analytics

import { Ok, Err, Some, None, makeTestState, type Result, type Option, type ValidationError } from "../runtime.js";
import * as shortener_analytics from "./../shortener/analytics.js";
import * as shortener_core from "./../shortener/core.js";

class ExpectationError extends Error {
  location: string;
  start: number;
  end: number;
  constructor(location: string, start: number, end: number, detail: string) {
    super(`${detail}\n  at ${location}`);
    this.location = location;
    this.start = start;
    this.end = end;
  }
}
function __bynkExpectFailure(location: string, start: number, end: number, detail: string) {
  return new ExpectationError(location, start, end, detail);
}
function __bynkExpect(cond: boolean, location: string, start: number, end: number, detail: string): void {
  if (!cond) { throw __bynkExpectFailure(location, start, end, detail); }
}
function __bynkShow(v: unknown): string {
  try { return typeof v === "bigint" ? String(v) : (JSON.stringify(v) ?? String(v)); } catch { return String(v); }
}

function makeTestDeps() {
  return {  };
}

async function test_a_fresh_Hits_key_reads_count_as_0() {
  try {
    shortener_analytics.__resetAgents();
    const deps = makeTestDeps();
    const { AnalyticsError, Hits, __makeHits, count, track } = shortener_analytics as any;
    const { ShortCode, Url } = shortener_core as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/shortener/analytics.bynk:32:20", 1358, 1363, "expect false");
          }
          case "Ok": {
            const code = __d.value;
            const reading = await count.call(code, deps);
            switch (reading.tag) {
              case "Ok": {
                const total = reading.value;
                return __bynkExpect((total === 0), "tests/shortener/analytics.bynk:36:25", 1458, 1468, "expect total == 0");
              }
              case "Err": {
                return __bynkExpect((false), "tests/shortener/analytics.bynk:37:25", 1493, 1498, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(ShortCode.of("fresh1")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_recording_a_hit_returns_a_running_total() {
  try {
    shortener_analytics.__resetAgents();
    const deps = makeTestDeps();
    const { AnalyticsError, Hits, __makeHits, count, track } = shortener_analytics as any;
    const { ShortCode, Url } = shortener_core as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/shortener/analytics.bynk:45:20", 1614, 1619, "expect false");
          }
          case "Ok": {
            const code = __d.value;
            const result = await track.call(code, deps);
            switch (result.tag) {
              case "Ok": {
                const total = result.value;
                return __bynkExpect((total === 1), "tests/shortener/analytics.bynk:49:25", 1712, 1722, "expect total == 1");
              }
              case "Err": {
                return __bynkExpect((false), "tests/shortener/analytics.bynk:50:25", 1747, 1752, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(ShortCode.of("abc123")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_two_hits_on_the_same_code_accumulate() {
  try {
    shortener_analytics.__resetAgents();
    const deps = makeTestDeps();
    const { AnalyticsError, Hits, __makeHits, count, track } = shortener_analytics as any;
    const { ShortCode, Url } = shortener_core as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/shortener/analytics.bynk:58:20", 1865, 1870, "expect false");
          }
          case "Ok": {
            const code = __d.value;
            const __r0 = await track.call(code, deps);
            const second = await track.call(code, deps);
            switch (second.tag) {
              case "Ok": {
                const total = second.value;
                return __bynkExpect((total === 2), "tests/shortener/analytics.bynk:63:25", 1992, 2002, "expect total == 2");
              }
              case "Err": {
                return __bynkExpect((false), "tests/shortener/analytics.bynk:64:25", 2027, 2032, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(ShortCode.of("abc123")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

async function test_count_reads_back_the_current_total_without_incrementing() {
  try {
    shortener_analytics.__resetAgents();
    const deps = makeTestDeps();
    const { AnalyticsError, Hits, __makeHits, count, track } = shortener_analytics as any;
    const { ShortCode, Url } = shortener_core as any;
    void (await (async (__d) => {
        switch (__d.tag) {
          case "Err": {
            return __bynkExpect((false), "tests/shortener/analytics.bynk:72:20", 2164, 2169, "expect false");
          }
          case "Ok": {
            const code = __d.value;
            const __r0 = await track.call(code, deps);
            const reading = await count.call(code, deps);
            switch (reading.tag) {
              case "Ok": {
                const total = reading.value;
                return __bynkExpect((total === 1), "tests/shortener/analytics.bynk:77:25", 2293, 2303, "expect total == 1");
              }
              case "Err": {
                return __bynkExpect((false), "tests/shortener/analytics.bynk:78:25", 2328, 2333, "expect false");
              }
            }
            throw new Error("non-exhaustive match");
          }
        }
        throw new Error("non-exhaustive match");
      })(ShortCode.of("zzz999")));
    return { pass: true };
  } catch (e) {
    if (e instanceof ExpectationError) {
      return { pass: false, error: { message: e.message, location: e.location } };
    }
    return { pass: false, error: { message: String(e), location: "unknown" } };
  }
}

export async function run() {
  const results = [];
  results.push({ name: "a fresh Hits key reads count as 0", ...(await test_a_fresh_Hits_key_reads_count_as_0()) });
  results.push({ name: "recording a hit returns a running total", ...(await test_recording_a_hit_returns_a_running_total()) });
  results.push({ name: "two hits on the same code accumulate", ...(await test_two_hits_on_the_same_code_accumulate()) });
  results.push({ name: "count reads back the current total without incrementing", ...(await test_count_reads_back_the_current_total_without_incrementing()) });
  return results;
}
