// Generated by karnc — do not edit by hand.
// composition root for `commerce.orders` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
  COMMERCE_PAYMENT: ServiceBinding;
}

export function compose(env: Env) {
  const deps = { env };
  return {
    async placeOrder(total: any) {
      return handlers.placeOrder.call(total, deps);
    },
  };
}
