// Generated by karnc — do not edit by hand.
// composition root

import * as shortener_analytics from "./shortener/analytics.js";
import * as shortener_links from "./shortener/links.js";

export function composeApp() {
  const shortener_analyticsDeps = {  };
  const shortener_analyticsSurface = shortener_analytics.makeSurface(shortener_analyticsDeps);
  const shortener_linksDeps = { CodeGen: new shortener_links.FixedCodeGen(), surface: { Analytics: shortener_analyticsSurface } };
  const shortener_linksSurface = shortener_links.makeSurface(shortener_linksDeps);

  return {
    analytics: shortener_analyticsSurface,
    links: shortener_linksSurface,
  };
}
