#!/usr/bin/env bash
# Generate (or verify) llms-full.txt — the entire Bynk Book inlined into one
# file for LLM context. It is a mechanical concatenation of every page in
# docs/src/SUMMARY.md, in reading order, so it is a *generated artifact*: never
# edit llms-full.txt by hand. Edit the Book, then regenerate.
#
# The curated index with the hand-written primer is llms.txt — that one is
# authored, not generated, and this script does not touch it.
#
#   scripts/build-llms-full.sh            regenerate llms-full.txt in place
#   scripts/build-llms-full.sh --check    fail (non-zero) if it is out of date
#
# CI runs `--check` in the docs job; a drift fails the PR. The version banner is
# read from [workspace.package] in Cargo.toml, so a `bump-version.sh` run (which
# also regenerates this file) keeps it in lock-step.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="llms-full.txt"
SUMMARY="docs/src/SUMMARY.md"

mode="write"
case "${1:-}" in
	--check) mode="check" ;;
	--write | "") mode="write" ;;
	-h | --help)
		sed -n '2,17p' "$0"
		exit 0
		;;
	*)
		echo "usage: $0 [--write|--check]" >&2
		exit 2
		;;
esac

# Single source of truth for the current version: the [workspace.package]
# version in Cargo.toml. The banner tracks MAJOR.MINOR, matching the Book's
# "currently vX.Y" banners (guarded by bynkc/tests/doc_version.rs).
ver="$(sed -n '/^\[workspace\.package\]/,/^\[/ s/^version = "\([^"]*\)".*/\1/p' Cargo.toml | head -1)"
mm="${ver%.*}"
sep="# ────────────────────────────────────────────────────────────"

generate() {
	cat <<HEADER
# Bynk — Full Documentation

> Bynk is a statically typed, architecture-first programming language for building
> services. Its contexts, services, agents, and the types that flow between them are
> part of the language, not a convention layered on top. Bynk compiles to typed
> TypeScript and targets Cloudflare Workers. It is pre-1.0 (currently v$mm).

This file inlines the complete Bynk Book — every tutorial, guide, reference page,
and the normative specification — concatenated in reading order. It is the
expanded companion to \`llms.txt\` (the curated index). Each page below is preceded
by a \`# ──\` marker giving its source path under \`docs/src/\`. The Book documents
what compiles today; features marked "planned" are deferred.

This file is generated by scripts/build-llms-full.sh — do not edit it by hand;
edit the Book under docs/src/ and regenerate. For the curated index with a
shorter primer, see \`llms.txt\`.
HEADER

	# Pages in SUMMARY.md order. The grep pulls every (relative/path.md) link
	# target; SUMMARY.md lists each page exactly once, in reading order.
	grep -oE '\(([a-zA-Z0-9._/-]+\.md)\)' "$SUMMARY" | sed 's/[()]//g' | while read -r f; do
		path="docs/src/$f"
		if [ ! -f "$path" ]; then
			echo "build-llms-full: missing source referenced by SUMMARY.md: $path" >&2
			exit 1
		fi
		printf '\n\n%s\n# Source: %s\n%s\n\n' "$sep" "$path" "$sep"
		cat "$path"
	done
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
generate >"$tmp"

if [ "$mode" = "check" ]; then
	if ! diff -u "$OUT" "$tmp" >/dev/null 2>&1; then
		echo "error: $OUT is out of date." >&2
		echo "Regenerate with: scripts/build-llms-full.sh" >&2
		echo >&2
		diff -u "$OUT" "$tmp" >&2 || true
		exit 1
	fi
	echo "$OUT is up to date ($(grep -c '^# Source:' "$OUT") pages)."
else
	mv "$tmp" "$OUT"
	trap - EXIT
	echo "wrote $OUT ($(grep -c '^# Source:' "$OUT") pages, v$mm)."
fi
