// Generated by bynkc — do not edit by hand.
// composition root for `jobs` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async cron_sweeper_0() {
      return handlers.sweeper.cron_sweeper_0(deps);
    },
    async cron_sweeper_1() {
      return handlers.sweeper.cron_sweeper_1(deps);
    },
  };
}
