// Generated by bynkc — do not edit by hand.
// commons test

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function isOk(r: Result<number, string>): boolean {
  return r.tag === "Ok";
}

