// Generated by bynkc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export async function doWork(n: number): Promise<number> {
  const inc = n + 1;
  const result = await Promise.resolve(inc * 2);
  return result;
}

