// Generated by karnc — do not edit by hand.
// composition root for `greet` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = { Clock: new handlers.FixedClock() };
  return {
    async hello(name: any) {
      return handlers.hello.call(name, deps);
    },
  };
}
