// Generated by karnc — do not edit by hand.
// commons test

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function double(n: number): number {
  const x: number = n + n;
  return x;
}

