// Generated by bynkc — do not edit by hand.
// commons docs.demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

/**
 * Add two integers together.
 */
export function add(a: number, b: number): number {
  return a + b;
}

