// Generated by bynkc — do not edit by hand.
// context demo.svc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Logger {
  log(message: string): Promise<void>;
  error(message: string): Promise<void>;
}

export const LoggerToken: unique symbol = Symbol("Logger");

