// Generated by bynkc — do not edit by hand.
// context docs.archive

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, type DurableObjectState, type DurableObjectNamespace, StateRegistry, makeAgent, rehydrationViolation, type JsonValue, type BoundaryError, __bynkBytesEqual, __bynkBytesToBase64, __bynkBytesFromBase64, __bynkBytesDecodeUtf8 } from "../runtime.js";

import { Doc as __CommonsDoc } from "./model.js";

export type Doc = __CommonsDoc & { readonly __ctxBrand: "docs.archive" };

export interface Blob {
  readonly label: string;
  readonly bytes: Uint8Array;
}

export const Blob = {
};

export interface VaultState {
  readonly latest: Blob;
}

const __VaultRegistry = new StateRegistry();
function __zeroOfVaultState(): VaultState { return { latest: { label: "", bytes: new Uint8Array() } }; }

function __rehydrateVaultState(s: VaultState): void {
  { const __r = deserialise_Blob((s.latest as unknown as JsonValue), "latest"); if (__r.tag === "Err") throw rehydrationViolation("Vault", __r.error); }
}

export class Vault {
  state: DurableObjectState;
  constructor(state: DurableObjectState) {
    this.state = state;
  }

  private async loadState(): Promise<VaultState> {
    const stored = await this.state.storage.get<VaultState>("state");
    if (stored === undefined) return __zeroOfVaultState();
    const __merged = { ...__zeroOfVaultState(), ...stored };
    __rehydrateVaultState(__merged);
    return __merged;
  }

  private async commitState(s: VaultState): Promise<void> {
    await this.state.storage.put("state", s);
  }

  async save(b: Blob, deps: {}): Promise<Result<number, void>> {
    const __state = { ...(await this.loadState()) };
    const __result = await (async () => {
      __state.latest = b;
      return Ok((b.bytes).length);
    })();
    await this.commitState(__state);
    return __result;
  }

}

export function __makeVault(key: string, env?: { VAULT?: DurableObjectNamespace }): Vault {
  return makeAgent(__VaultRegistry, env?.VAULT, key, (state) => new Vault(state));
}

export const intake = {
  async call(d: Doc, deps: {}): Promise<Result<number, void>> {
    return Ok((d.body).length);
  },
};

export function __resetAgents(): void {
  __VaultRegistry.reset();
}

export interface DocsArchiveDeps {
}

export function makeSurface(deps: DocsArchiveDeps) {
  return {
    async intake(d: Doc): Promise<Result<number, void>> {
      return intake.call(d, deps);
    },
  };
}

export function serialise_Blob(value: Blob): JsonValue {
  return {
    label: value.label as JsonValue,
    bytes: __bynkBytesToBase64(value.bytes) as JsonValue,
  };
}

export function deserialise_Blob(json: JsonValue, path: string = "$"): Result<Blob, BoundaryError> {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return Err({ kind: "StructuralMismatch", path, expected: "object", actual: typeof json });
  }
  const obj = json as { [k: string]: JsonValue };
  if (typeof obj["label"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.label`, expected: "string", actual: typeof obj["label"] });
  }
  const __label = obj["label"];
  if (typeof obj["bytes"] !== "string") {
    return Err({ kind: "StructuralMismatch", path: `${path}.bytes`, expected: "base64 string", actual: typeof obj["bytes"] });
  }
  const __b_bytes = __bynkBytesFromBase64(obj["bytes"]);
  if (__b_bytes.tag === "None") {
    return Err({ kind: "StructuralMismatch", path: `${path}.bytes`, expected: "base64 string", actual: "invalid base64" });
  }
  const __bytes = __b_bytes.value;
  return Ok({ label: __label, bytes: __bytes } as Blob);
}


