// Generated by bynkc — do not edit by hand.
// commons docs.model

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Doc {
  readonly name: string;
  readonly body: Uint8Array;
}

export const Doc = {
};

