// Generated by karnc — do not edit by hand.
// Worker entry point for context `commerce.orders`.

import { Ok, Err, type Result, type JsonValue, type BoundaryError, boundaryError, matchPath, httpResultToResponse } from "../../runtime.js";
import { compose, type Env } from "./compose.js";
import * as handlers from "./handlers.js";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;
    const surface = compose(env);
    try {
      if (path.startsWith("/_karn/call/")) {
        const servicePath = path.slice("/_karn/call/".length);
        switch (servicePath) {
          case "placement": {
            const args = await request.json() as JsonValue;
            const __r_total = handlers.deserialise_Money(args, "$");
            if (__r_total.tag === "Err") return new Response(JSON.stringify(__r_total.error), { status: 400, headers: { "content-type": "application/json" } });
            const total = __r_total.value;
            const result = await surface.placement(total);
            const body = handlers.serialise_Result_Unit_OrderError(result);
            return new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
          }
          default:
            return new Response("Not found", { status: 404 });
        }
      }

      {
        if (method === "POST" && path === "/orders") {
          let __body_json: JsonValue;
          try {
            __body_json = (await request.json()) as JsonValue;
          } catch (e) {
            return new Response(JSON.stringify({ kind: "MalformedJson", details: String(e) }), { status: 400, headers: { "content-type": "application/json" } });
          }
          const __r_body = handlers.deserialise_CreateOrderRequest(__body_json, "$");
          if (__r_body.tag === "Err") return new Response(JSON.stringify(__r_body.error), { status: 400, headers: { "content-type": "application/json" } });
          const body = __r_body.value;
          const result = await surface.http_POST_orders(body);
          return httpResultToResponse(result, handlers.serialise_OrderView);
        }
      }
      return new Response("Not Found", { status: 404 });
    } catch (e) {
      return new Response(String(e), { status: 500 });
    }
  },
};
