// Generated by karnc — do not edit by hand.
// commons test

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function absVal(n: number): number {
  return (n < 0 ? -n : n);
}

