// Generated by bynkc — do not edit by hand.
// commons commerce.money

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export function discount(p: number, pct: number): number {
  return p - Math.trunc((p * pct) / 100);
}

