// Generated by karnc — do not edit by hand.
// commons demo

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "./runtime.js";

export function add3(a: number, b: number, c: number): number {
  return a + b + c;
}

