// Generated by karnc — do not edit by hand.
// composition root for `hooks` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async http_POST_hooks_event(body: any) {
      return handlers.api.http_POST_hooks_event(body, deps);
    },
  };
}
