// Generated by bynkc — do not edit by hand.
// composition root

import * as ids_gen from "./ids/gen.js";
import * as bynk__binding from "./bynk-node.js";

export function composeApp() {
  const ids_genDeps = { Clock: new bynk__binding.ClockProvider(), Secrets: new bynk__binding.SecretsProvider() };
  const ids_genSurface = ids_gen.makeSurface(ids_genDeps);

  return {
    gen: ids_genSurface,
  };
}
