// Generated by bynkc — do not edit by hand.
// composition root for `feed` Worker.

import { type ServiceBinding } from "../../runtime.js";
import * as handlers from "./handlers.js";

export interface Env {
}

export function compose(env: Env) {
  const deps = {  };
  return {
    async http_GET_ticks() {
      return handlers.Feed.http_GET_ticks(deps);
    },
    async http_GET_feed_Param_mode(mode: any) {
      return handlers.Feed.http_GET_feed_Param_mode(mode, deps);
    },
  };
}
