// Generated by bynkc — do not edit by hand.
// context feed

import { Ok, Err, Some, None, type Result, type Option, type ValidationError, HttpResult, type JsonValue, type BoundaryError, type ServiceBinding, callService, boundaryError } from "../../runtime.js";

export const Feed = {
  async http_GET_ticks(deps: {}): Promise<HttpResult<void>> {
    return HttpResult.Streaming((async function* (__s) { const __n = 3; if (__n <= 0) { return; } let __i = 0; for await (const __e of __s) { yield __e; if (++__i >= __n) { return; } } })((async function* () { for (const __e of ["tick-1", "tick-2", "tick-3"]) { yield __e; } })()));
  },
  async http_GET_feed_Param_mode(mode: string, deps: {}): Promise<HttpResult<void>> {
    return (mode === "live" ? HttpResult.Streaming((async function* (__s) { const __n = 2; if (__n <= 0) { return; } let __i = 0; for await (const __e of __s) { yield __e; if (++__i >= __n) { return; } } })((async function* (__s) { for await (const __e of __s) { yield ((s) => s)(__e); } })((async function* () { for (const __e of ["a", "b", "c"]) { yield __e; } })()))) : HttpResult.NotFound);
  },
};

