// Generated by bynkc — do not edit by hand.
// context demo.svc

import { Ok, Err, Some, None, type Result, type Option, type ValidationError } from "../runtime.js";

export interface Logger {
  log(message: string): Promise<void>;
}

export const LoggerToken: unique symbol = Symbol("Logger");

export const silent = {
  async call(deps: { Logger: Logger }): Promise<void> {
    return undefined;
  },
};

export interface DemoSvcDeps {
  readonly Logger: Logger;
}

export function makeSurface(deps: DemoSvcDeps) {
  return {
    async silent(): Promise<void> {
      return silent.call(deps);
    },
  };
}

